services:
  # 1. LE BACKEND (API)
  api:
    build: ./backend
    restart: always
    environment:
      # Docker va chercher automatiquement la valeur dans le fichier .env
      - DATABASE_URL=${DATABASE_URL}
    command: uvicorn API:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  # 2. LE FRONTEND (Dashboard)
  ui:
    build: ./frontend
    restart: always
    environment:
      # Même chose ici, appel à la variable sécurisée
      - DATABASE_URL=${DATABASE_URL}
      - API_URL=http://api:8000
    command: python UI.py
    ports:
      - "8053:8053"
    depends_on:
      - api